### ISSUE TITLE
Duration seems broken in 4.0.0-RC10

### ISSUE THREAD

**Issue by russwyte** [zio/zio-config#1090]
I expect this example to succeed:
```scala
import zio.*
import zio.config.*
import zio.config.magnolia.*
import zio.config.typesafe.*

object Example extends ZIOAppDefault:
  case class Foo(duration: Duration)
  val run = ConfigProvider
    .fromHoconString("duration = 10.seconds")
    .load(deriveConfig[Foo])
    .debug
end Example
```
Instead it fails with:
`(Invalid data at duration: Expected a duration value, but found 10.seconds)`

**Comment by bilal-fazlani** [comment]
Why is closed? I am also facing issue 

```
Expected a duration value, but found 30m
```

**Comment by afsalthaj** [comment]
@bilal-fazlani  This goes back to again `ZIO`.
I have pealed off components of zio-config, and tried just with ZIO


```scala

object Example extends ZIOAppDefault {
  case class Foo(duration: Duration)

  val run = ConfigProvider
    .fromMap(Map("duration" -> "10.seconds"))
    .load(Config.duration("duration"))
    .debug
}

```

and this produce the same error:

```scala
<FAIL> Fail((Invalid data at duration: Expected a duration value, but found 10.seconds),Stack trace for thread "zio-fiber-4":
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:313)
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:314)
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:315)
	at zio.config.examples.Example.run(DurationApp.scala:12)
	at zio.config.examples.Example.run(DurationApp.scala:13))
timestamp=2023-03-06T14:15:17.018552Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" zio.Config$Error$InvalidData: (Invalid data at duration: Expected a duration value, but found 10.seconds)
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:313)
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:314)
	at zio.ConfigProvider.Flat.util.parsePrimitive(ConfigProvider.scala:315)
	at zio.config.examples.Example.run(DurationApp.scala:12)
	at zio.config.examples.Example.run(DurationApp.scala:13)"
```


I will see why this happens. But I am closing this issue in zio-config and create a new one in ZIO, to avoid confusion
