### ISSUE TITLE
unable to read `zio.Duration`

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-config#1096]
zioConfigVersion   :  4.0.0-RC10

```scala
object TestApp3 extends zio.ZIOAppDefault:
  val configString = "duration = 5m"
  val config       = Config.duration("duration")

  override val bootstrap: ZLayer[Any, Nothing, Unit] =
    Runtime.setConfigProvider(
      TypesafeConfigProvider
        .fromHoconString(configString)
    )

  def run = ZIO
    .config(config)
    .debug("result")
    .exitCode
```

Error:

```
<FAIL> result: Fail((Invalid data at duration: Expected a duration value, but found 5m),Stack trace for thread "zio-fiber-4":
        at example.TestApp3.run(TestApp.scala:131)
        at example.TestApp3.run(TestApp.scala:132)
        at example.TestApp3.run(TestApp.scala:133))
```

**Comment by bilal-fazlani** [comment]
PS: This used to in earlier versions

**Comment by afsalthaj** [comment]
https://github.com/zio/zio-config/issues/1090#issuecomment-1456217598

**Comment by afsalthaj** [comment]
Closing this issue here as it is related to zio core
