### ISSUE TITLE
Upgrade to zio 1.0.0-RC18

### ISSUE THREAD

**Issue by cdelmas** [zio/zio-config#216]
There are some incompatibilities when trying to use the current zio-config version with the brand new zio 1.0.0-RC18. I get this error (I upgraded my app to the latest zio this morning)
```
[E] Exception in thread "main" java.lang.NoSuchMethodError: zio.IO$.fail(Ljava/lang/Object;)Lzio/ZIO;
[E] 	at zio.config.ConfigSource$.$anonfun$empty$1(ConfigSource.scala:30)
[E] 	at zio.config.ConfigSource.$anonfun$orElse$1(ConfigSource.scala:15)
[E] 	at zio.config.ReadFunctions.loop$1(ReadFunctions.scala:18)
[E] 	at zio.config.ReadFunctions.loop$1(ReadFunctions.scala:46)
[E] 	at zio.config.ReadFunctions.loop$1(ReadFunctions.scala:82)
[E] 	at zio.config.ReadFunctions.loop$1(ReadFunctions.scala:46)
[E] 	at zio.config.ReadFunctions.read(ReadFunctions.scala:128)
[E] 	at zio.config.ReadFunctions.read$(ReadFunctions.scala:8)
[E] 	at zio.config.package$.read(package.scala:3)
[E] 	at Main$.loadConfig(Main.scala:68)
[E] 	at Main$.run(Main.scala:46)
[E] 	at zio.ManagedApp$$anon$1.run(ManagedApp.scala:29)
[E] 	at zio.App.$anonfun$main$1(App.scala:56)
[E] 	at zio.Runtime.unsafeRunAsync(Runtime.scala:110)
[E] 	at zio.Runtime.unsafeRunAsync$(Runtime.scala:91)
[E] 	at zio.ManagedApp$$anon$1.unsafeRunAsync(ManagedApp.scala:27)
[E] 	at zio.Runtime.unsafeRunSync(Runtime.scala:80)
[E] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
[E] 	at zio.ManagedApp$$anon$1.unsafeRunSync(ManagedApp.scala:27)
[E] 	at zio.Runtime.unsafeRun(Runtime.scala:57)
[E] 	at zio.Runtime.unsafeRun$(Runtime.scala:56)
[E] 	at zio.ManagedApp$$anon$1.unsafeRun(ManagedApp.scala:27)
[E] 	at zio.App.main(App.scala:64)
[E] 	at zio.App.main$(App.scala:52)
[E] 	at zio.ManagedApp$$anon$1.main(ManagedApp.scala:27)
[E] 	at zio.ManagedApp.main(ManagedApp.scala:32)
[E] 	at zio.ManagedApp.main$(ManagedApp.scala:32)
[E] 	at Main$.main(Main.scala:24)
[E] 	at Main.main(Main.scala)
```

I forked the project, and trying to compile with RC-18 leads to some errors:
````
[error] /zio-config/core/src/main/scala/zio/config/Config.scala:7:26: value Live is not a member of object zio.system.System
[error] did you mean live?
[error] import zio.system.System.Live.system.lineSeparator
[error]                          ^
[error] /zio-config/core/src/main/scala/zio/config/Config.scala:68:11: not found: value lineSeparator
[error]           lineSeparator.flatMap(
[error]           ^
[error] /zio-config/core/src/main/scala/zio/config/ConfigSource.scala:4:26: value Live is not a member of object zio.system.System
[error] did you mean live?
[error] import zio.system.System.Live.system
[error]                          ^
[error] /zio-config/core/src/main/scala/zio/config/ConfigSource.scala:36:9: not found: value system
[error]         system
[error]         ^
[error] /zio-config/core/src/main/scala/zio/config/ConfigSource.scala:67:9: not found: value system
[error]         system
[error]         ^
[error] 5 errors found
[error] (zio-config / Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed 4 mars 2020 14:40:40
```

**Comment by afsalthaj** [comment]
This is done
