### ISSUE TITLE
Very slow performance with large number of env vars.

### ISSUE THREAD

**Issue by notxcain** [zio/zio-config#418]
When you run your app on Kubernetes there are a lot of env vars defined. At least two for each service. So in my case there are 800 of env vars like `LONG_SERVICE_NAME_HOST` and `ANOTHER_LONG_SERVICE_NAME_PORT`. 

And it seems that config loading is stuck forever in `PropertyTree#mergeAll`.

**Comment by afsalthaj** [comment]
@notxcain thanks for reporting the issue. Could you give an example Config that resulting in hanging for ever?

**Comment by amitksingh1490** [comment]
+1

**Comment by tusharmath** [comment]
For our use-case (100kb of env variables) we get an out of memory error —

```
java.lang.OutOfMemoryError: Java heap space
	at scala.collection.immutable.BitmapIndexedMapNode.copyAndSetNode(HashMap.scala:937)
	at scala.collection.immutable.BitmapIndexedMapNode.updated(HashMap.scala:730)
	at scala.collection.immutable.HashMap.updated(HashMap.scala:152)
	at scala.collection.immutable.HashMap.updated(HashMap.scala:39)
	at scala.collection.immutable.MapOps.$plus(Map.scala:133)
	at scala.collection.immutable.MapOps.$plus$(Map.scala:133)
	at scala.collection.immutable.AbstractMap.$plus(Map.scala:641)
	at zio.config.PropertyTree.$anonfun$merge$6(PropertyTree.scala:135)
	at zio.config.PropertyTree$$Lambda$547/0x0000000100330040.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:246)
	at zio.config.PropertyTree.$anonfun$merge$1(PropertyTree.scala:135)
	at zio.config.PropertyTree$$Lambda$543/0x000000010032d040.apply(Unknown Source)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
	at zio.config.PropertyTree.merge(PropertyTree.scala:128)
	at zio.config.PropertyTree.merge$(PropertyTree.scala:123)
	at zio.config.PropertyTree$Record.merge(PropertyTree.scala:223)
	at zio.config.PropertyTree$.$anonfun$mergeAll$2(PropertyTree.scala:277)
	at zio.config.PropertyTree$$$Lambda$541/0x000000010032b840.apply(Unknown Source)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at zio.config.PropertyTree$.$anonfun$mergeAll$1(PropertyTree.scala:277)
	at zio.config.PropertyTree$$$Lambda$539/0x000000010032a840.apply(Unknown Source)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:168)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:164)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at zio.config.PropertyTree$.mergeAll(PropertyTree.scala:276)
	at zio.config.PropertyTree$.unflatten(PropertyTree.scala:271)
	at zio.config.ConfigSourceStringModule$ConfigSource$.fromMapInternal(ConfigSourceModule.scala:439)
	at zio.config.ConfigSourceStringModule$ConfigSource$.fromMap(ConfigSourceModule.scala:226)
	at zio.config.ConfigSourceStringModule$ConfigSource$.$anonfun$fromSystemEnv$3(ConfigSourceModule.scala:386)
	at zio.config.ConfigSourceStringModule$ConfigSource$$$Lambda$124/0x00000001001b5840.apply(Unknown Source)
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
```

**Comment by afsalthaj** [comment]
Could you also give the details of the source (Example: is it key -> value property file or HOCON) ? What's the target data structure (Example: case class, Map?)

**Comment by notxcain** [comment]
@afsalthaj I've sanitized our env vars https://gist.github.com/notxcain/c21f24e2d1f8e8e692512acdb496c599.

**Comment by afsalthaj** [comment]
Sure. Could you also share the code that tries to retrieve the config?

**Comment by notxcain** [comment]
@afsalthaj just use this map in your example.

**Comment by afsalthaj** [comment]
@notxcain Worked
![image](https://user-images.githubusercontent.com/7448613/97437346-6dddff00-1977-11eb-913f-b73a8c339bb8.png)

**Comment by notxcain** [comment]
Damn, I must've oversanitized something. It fails on unsanitized env vars. Let me recheck.

**Comment by afsalthaj** [comment]
@notxcain Sure, thanks.
Meanwhile I am looking at @tusharmath's example that has a much more complicated retrieval by passing delimiter to 100KB key value pair.

**Comment by afsalthaj** [comment]
@notxcain  See if you are also passing delimiters. 
Example: `val mapSource = ConfigSource.fromMap(source, keyDelimiter = Some('_'))`
Then we all are on the same page.

**Comment by notxcain** [comment]
Ah, of course! Sorry I didn't mention that.

**Comment by notxcain** [comment]
@afsalthaj so now you see it too?

**Comment by afsalthaj** [comment]
Yes, only when passing the delimiters. That's how I reproduced the issue. 
Fixing mergeAll function now

**Comment by notxcain** [comment]
@afsalthaj how is it going? Did you find the solution?

**Comment by notxcain** [comment]
@afsalthaj sorry to bother you, but do you have an update?

**Comment by afsalthaj** [comment]
@notxcain could I get back to you in a while. Could filter the values first in sys.env and then pass it as a reduced map to zio-config for the time being?

**Comment by afsalthaj** [comment]
@notxcain give me a bit more time, and I hope il fix it soon. Currently busy with Api docs and zio-columnar

**Comment by notxcain** [comment]
As a workaround, we used system properties populated from env vars.

**Comment by notxcain** [comment]
Have you thought about lazy source design? So that you don't have to convert all the env vars, and just access on demand.

**Comment by afsalthaj** [comment]
@notxcain  Sorry to get back late. I was really busy with some of the other changes.

The memory issue comes into picture when there are large number of environment variables in the source, and we need a nested behaviour (explicit passing for delimiters) out of it. 

The quick fix for you is not to pass delimiters if there are too many delimited key-value pairs in flattened sources.
We will be looking at a proper solution than jumping on to a quick hack :)

Thanks for the patience.

**Comment by jdegoes** [comment]
A mutable implementation of `mergeAll` would fix this, as would, potentially, making source more lazy. I think I'd prefer the former as if you have thousands of env variables inside a property tree, laziness won't help.

Anyone want to volunteer for a mutable version of `mergeAll`? A good exercise in high-performance functional Scala.

**Comment by tusharmath** [comment]
@jdegoes That would be me :D

**Comment by jdegoes** [comment]
@tusharmath Awesome! Let me know if you would like to pair on it or need additional clarification! 🙏

**Comment by remiguittaut** [comment]
Hi guys, I see that there is a standing PR. That problem is a bit of a blocker for me. Any idea about when this can be deployed?

**Comment by afsalthaj** [comment]
There is a slight redesign going on
at the configsource side. We have an eye on this.
